name: CI - Ejecución de Pruebas Unitarias con Pytest
run-name: Ejecutar pruebas unitarias con Pytest en Python (🧪)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Clonar el repositorio y obtener el código fuente
        uses: actions/checkout@v3

      - name: 🔧 Configurar entorno de Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 📦 Instalar dependencias del proyecto
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest-html

      - name: 🛠️ Generar archivo de pruebas unitarias si no existe
        run: python generate_tests.py

      - name: 🧪 Ejecutar pruebas unitarias con Pytest y generar HTML
        run: |
          PYTHONPATH=. pytest -v --disable-warnings --html=report.html
          echo "✅ Pruebas ejecutadas, verificando existencia de report.html"
          ls -lah

      - name: 📤 Subir reporte de pruebas en HTML a GitHub Actions
        uses: actions/upload-artifact@v4
        with:
          name: pytest-report-html
          path: report.html

